
 export const ArrayIconCategory=[
     {
         name:' beer',
         URL:require('../asset/iconCategory/Food/beer.png')
     },
     {
        name:'aubergine',
        URL:require('../asset/iconCategory/Food/aubergine.png')
    },
    {
        name:'birthdayCake',
        URL:require('../asset/iconCategory/Food/birthday-cake.png')
    },
    {
        name:'biscuit',
        URL:require('../asset/iconCategory/Food/biscuit.png')
    },
    {
        name:'bread',
        URL:require('../asset/iconCategory/Food/bread.png')
    },
    {
        name:'breakfast',
        URL:require('../asset/iconCategory/Food/breakfast.png')
    },
    {
        name:'coffee',
        URL:require('../asset/iconCategory/Food/coffee.png')
    },
    {
        name:'fish',
        URL:require('../asset/iconCategory/Food/fish.png')
    },
    {
        name:'milk',
        URL:require('../asset/iconCategory/Food/milk.png')
    },
    {
        name:'noodles',
        URL:require('../asset/iconCategory/Food/noodles.png')
    },
    {
        name:'pizaa',
        URL:require('../asset/iconCategory/Food/pizza.png')
    },
    {
        name:'rice',
        URL:require('../asset/iconCategory/Food/rice.png')
    },
    {
        name:'waterGlass',
        URL:require('../asset/iconCategory/Food/water-glass.png')
    },
    {
        name:'steak',
        URL:require('../asset/iconCategory/Food/steak.png')
    },
    {
        name:'apple',
        URL:require('../asset/iconCategory/Education/apple.png')
    },
    {
        name:'crayon',
        URL:require('../asset/iconCategory/Education/crayon.png')
    },
    {
        name:'graduationHat',
        URL:require('../asset/iconCategory/Education/graduation-hat.png')
    },
    {
        name:'couple',
        URL:require('../asset/iconCategory/Dating/couple.png')
    },
    {
        name:'bandAid',
        URL:require('../asset/iconCategory/Medical/band-aid.png')
    },
    {
        name:'eye',
        URL:require('../asset/iconCategory/Medical/eye.png')
    },
    {
        name:'tooth',
        URL:require('../asset/iconCategory/Medical/tooth.png')
    },
   
 ]